# Generated by Django 5.1.5 on 2025-02-13 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to='product', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'شرکت',
                'verbose_name_plural': 'شرکت ها',
            },
        ),
        migrations.CreateModel(
            name='ParagraphModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('text', models.TextField(verbose_name='متن')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraph', to='company_module.companymodel', verbose_name='شرکت')),
            ],
            options={
                'verbose_name': 'بند',
                'verbose_name_plural': 'بند ها',
            },
        ),
        migrations.CreateModel(
            name='RelatedImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product/related', verbose_name='تصویر')),
                ('paragraph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='company_module.paragraphmodel', verbose_name='بند')),
            ],
            options={
                'verbose_name': 'تصویر مرتبط',
                'verbose_name_plural': 'تصاویر مرتبط',
            },
        ),
    ]
