# Generated by Django 5.1.5 on 2025-02-13 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to='product', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'اختراع',
                'verbose_name_plural': 'اختراعات',
            },
        ),
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'تگ',
                'verbose_name_plural': 'تگ ها',
            },
        ),
        migrations.CreateModel(
            name='ParagraphModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('text', models.TextField(verbose_name='متن')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraph', to='project_module.projectmodel', verbose_name='اختراع')),
            ],
            options={
                'verbose_name': 'بند',
                'verbose_name_plural': 'بند ها',
            },
        ),
        migrations.CreateModel(
            name='RelatedImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product/related', verbose_name='تصویر')),
                ('paragraph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='project_module.paragraphmodel', verbose_name='بند')),
            ],
            options={
                'verbose_name': 'تصویر مرتبط',
                'verbose_name_plural': 'تصاویر مرتبط',
            },
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='tag',
            field=models.ManyToManyField(blank=True, to='project_module.tagmodel', verbose_name='تگ'),
        ),
    ]
