# Generated by Django 5.1.5 on 2025-02-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2000, verbose_name='متن')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='فرستاده شده در')),
                ('reply', models.BooleanField(default=True, verbose_name='پاسخ')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیام ها',
            },
        ),
    ]
